### ISSUE TITLE
Get GitHub username automatically from login session 

### ISSUE THREAD

**Issue by adityaoberai** [Haimantika/GitHub-roast#17]

**Comment by kitarp29** [comment]
Allah ka khauf kro Aditya Bhai! 😂
Kitna Open source kroge akele?

**Comment by adityaoberai** [comment]
> Allah ka khauf kro Aditya Bhai! 😂 Kitna Open source kroge akele?

arey sir maaf karein 🙈🙏

**Comment by kitarp29** [comment]
रावण में लाख बुराई थी... But he never stole anyone's idea and implemented it![images (3).jpeg](https://github.com/user-attachments/assets/73b7f2b5-d600-4bec-9aed-728f438dc9dd)

**Comment by adityaoberai** [comment]
> रावण में लाख बुराई थी... But he never stole anyone's idea and implemented it![images (3).jpeg](https://github.com/user-attachments/assets/73b7f2b5-d600-4bec-9aed-728f438dc9dd)
> 
> 

I didn't steal the idea for how to implement either, though 😏

**Comment by kitarp29** [comment]
FYI ![images (4) (1).jpeg](https://github.com/user-attachments/assets/25aca002-6b2d-4335-a531-4e2361d08d9b)
