### ISSUE TITLE
Adding a button to save the roast and share it as image

### ISSUE THREAD

**Issue by Haimantika** [Haimantika/GitHub-roast#2]
Currently, to share the roast, you need to take a screenshot and post. Adding a `Save` button, that makes it easy to share the roast on social media, would be a nice addition.

**Comment by VinnuReddy18** [comment]
@Haimantika i have done the setup locally into my computer , but while running, i am encountering an issue , do i need to have access to env files to run this locally?

**Comment by jagdishpatil02** [comment]
Hi, @Haimantika I have raised PR for this :)
