### ISSUE TITLE
Add gap between the input box and button

### ISSUE THREAD

**Issue by RushilJalal** [Haimantika/GitHub-roast#3]
Currently there is no gap between the input box and the button. 
I want to add a small gap between them. 
I believe this will make the design look better. 
Can I work on this?

**Comment by Haimantika** [comment]
Go ahead! Make sure to add screenshots.

**Comment by RushilJalal** [comment]
@Haimantika I think someone added a PR which already fixes this issue.
So closing this issue. Thanks.

**Comment by RushilJalal** [comment]
The PR supposed to fix this issue has been closed by the author.
Thus, I have reopened the issue and I will fix it.
